spring:
  application:
    name: job-ai-assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/job_ai_assistant
    username: jobai_user
    password: jobai123
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: gemma3:4b

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

google:
  client-id: ${GOOGLE_CLIENT_ID}

